#
# Build configuration file to run build on azure-pipelines
#
name: $(Build.Major).$(Build.Minor).$(DayOfMonth)$(rev:rr)

trigger: none

pr:
- main
- feature/*
- features/*
- release/*

schedules:
- cron: "0 9 * * Sat"
  displayName: 'Build for Component Governance'
  branches:
    include:
    - main
  always: true

variables:
  Build.Major: 0
  Build.Minor: 16
  Drops.Dir: $(Build.ArtifactStagingDirectory)/drops

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: Build/steps.yml
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: Build/steps.yml
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: Build/steps.yml


